name: Java CI

on: [push, pull_request, workflow_dispatch]

jobs:
  buildJar:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3.1.0

      - name: Set up JDK 17
        uses: actions/setup-java@v3.6.0
        with:
          java-version: 17
          distribution: temurin

      - name: Build the project
        run: |
          chmod +x gradlew
          ./gradlew dist --no-daemon --info --stacktrace

      - name: Run the project with Xvfb
        uses: GabrielBB/xvfb-action@v1
        with:
          run: |
            mkdir out
            cd out

            java -jar ../build/libs/DoTheyWorkThough.jar

      - name: Upload results
      - uses: actions/upload-artifact@v3
        with:
          name: Results
          path: out/*
